trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  storageAccount: "testeasecsa"
  containerName: "snapshot"

stages:
- stage: Check_container_exist
  jobs:
  - job:
    steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'test_sa'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            exist=$(az storage container exists --account-name "$(storageAccount)" --name "$(containerName)" --query [exists] -o tsv)
            echo $exist
            if [ "$exist" = "true" ]; then
              echo "Container exist"
            else
              echo "Container does´nt exist"
              az storage container create --name "$(containerName)" --account-name "$(storageAccount)"
            fi
